version: '2'
services:
  web:
    build: .
    command: bash -c "npm install; gulp"
    container_name: newsfeed-web-server
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - "8080:8080"
    working_dir: /newsfeed
    volumes:
      - .:/newsfeed

  db:
    image: postgres
    container_name: newsfeed-db
    environment:
      - POSTGRES_USER=zixian
      - POSTGRES_PASSWORD=NewsFeedIO
      - POSTGRES_DB=newsfeed
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    volumes:
      - ./db/data:/var/lib/postgresql/data/pgdata
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  redis:
    image: redis
