version: '2'
services:
  web:
    image: node
    command: bash -c "npm install -g gulp && npm install && gulp"
    container_name: newsfeed-web-server
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
    working_dir: /src
    volumes:
      - .:/src

  db:
    image: postgres
    container_name: newsfeed-db
    environment:
      - POSTGRES_USER=zixian
      - POSTGRES_PASSWORD=NewsFeedIO
      - POSTGRES_DB=newsfeed
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    volumes:
      - ./db/data:/var/lib/postgresql/data/pgdata
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
